#!/bin/bash
#autostart
xset -b
xinput set-prop 12 275 1
xinput set-prop 12 277 1
# grid layout
obsetlayout 0 2 2 0
# background (wallpaper) image
sh /home/ryan/.fehbg
# audio control panel item
alsa-tray +tray &
tint2 -c .config/tint2/tint2rc &
conky &
firefox-aurora &
