#!/bin/bash
# AUTOSTART

# grid layout
obsetlayout 0 2 2 0

# background (wallpaper) image
/home/ryan/.fehbg

# drawer/panel
tint2 -c /home/ryan/.config/tint2/tint2rc &
# audio control panel item
alsa-tray --card=hw:0 +tray &

cd /home/ryan/.config/conky
conky -c conkyrc -q -d
cd /home/ryan

firefox-aurora &
